### ISSUE TITLE
'NoneType' object has no attribute 'resize'

### ISSUE THREAD

**Issue by ywaison** [CrystalWlz/OMEGAS#1]
Hello, thank you very much for your great works. When I run the command python run_gaussian.py -s data/ horse-m output/ horse-r 4, the code gives the following error, I don't know how to solve it, I hope to get your timely reply, thank you again！
![image](https://github.com/CrystalWlz/OMEGAS/assets/138007686/de07ba63-2233-4267-b8be-2c75ee86c6c6)

**Comment by okaytom** [comment]
Did anyone find the fix to this problem?
