### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization_dm'

### ISSUE THREAD

**Issue by Xiaohui-Song** [CrystalWlz/OMEGAS#5]
The dreamgaussian.gs_renderer_2D file is missing in the OMEGAS/dreamgaussian/ folder, and the diff_gaussian_rasterization_dm file in the same folder has not been uploaded. I would appreciate it if the author could provide an update. Thank you!"

**Comment by CrystalWlz** [comment]
We will update our code later.
