### ISSUE TITLE
do not have deva/inference/data/simple_video_reader 

### ISSUE THREAD

**Issue by lovewindzz** [CrystalWlz/OMEGAS#6]
hi,bro Today i try to run the code but when i get the origian doit-cloud by using colmap . when i run 'bash script/prepare_pseudo_label.sh mydata 1' i get an error which  was writting " File "/home/sx639/SJH/OMEGAS-master/Tracking-Anything-with-DEVA/demo/demo_automatic.py", line 11, in <module>
    from deva.inference.data.simple_video_reader import SimpleVideoReader, no_collate
ModuleNotFoundError: No module named 'deva.inference.data'" . so i check the code and i find the error from ERROR: No matching distribution found for deva-inference-data . 
thanks!

**Comment by CrystalWlz** [comment]
https://github.com/hkchengrex/Tracking-Anything-with-DEVA

**Comment by lovewindzz** [comment]
thanks，bro i got it
