### ISSUE TITLE
ImportError: cannot import name 'convert_camera_from_orbit_to_pytorch3d' from 'dreamgaussian.cam_utils' 

### ISSUE THREAD

**Issue by zuofy** [CrystalWlz/OMEGAS#7]
hi, when i run 'python dream_gaussian_2D.py --config configs/dream/dream_bear.yaml', i get an error which was writting "Traceback (most recent call last):
  File "/mnt/d/InterestIdea/OMEGAS/dream_gaussian_2D.py", line 25, in <module>
    from dreamgaussian.cam_utils import convert_camera_from_orbit_to_pytorch3d
ImportError: cannot import name 'convert_camera_from_orbit_to_pytorch3d' from 'dreamgaussian.cam_utils' (/mnt/d/InterestIdea/OMEGAS/dreamgaussian/cam_utils.py)" . 
I would appreciate it if the author could provide an update. Thank you!

**Comment by CrystalWlz** [comment]
This code is not actually used, please ignore this issue.
